# Generated by Django 3.1.4 on 2020-12-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0003_auto_20201202_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ITsupermanapp.category'),
        ),
    ]
