# Generated by Django 3.1.4 on 2020-12-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0009_auto_20201210_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='history',
            field=models.PositiveIntegerField(default=0, verbose_name='投稿id履歴'),
        ),
    ]
