# Generated by Django 3.1.4 on 2020-12-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0010_customuser_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='history',
            field=models.CharField(max_length=50, verbose_name='投稿id履歴'),
        ),
    ]
