# Generated by Django 3.1.4 on 2020-12-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0011_auto_20201214_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='like_post',
            field=models.ManyToManyField(blank=True, to='ITsupermanapp.PostModel', verbose_name='like'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='history',
            field=models.PositiveIntegerField(default=0, verbose_name='history'),
        ),
    ]
