# Generated by Django 3.1.3 on 2020-12-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0012_auto_20201219_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='history',
        ),
        migrations.AddField(
            model_name='customuser',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='history', to='ITsupermanapp.PostModel', verbose_name='history'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='like_post', to='ITsupermanapp.PostModel', verbose_name='like'),
        ),
    ]
