# Generated by Django 3.1.3 on 2020-12-29 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0013_questionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='tags',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
