# Generated by Django 3.1.3 on 2020-12-29 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0014_auto_20201229_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
