# Generated by Django 3.1.3 on 2020-12-30 05:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0015_auto_20201229_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='Answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
