# Generated by Django 3.1.3 on 2020-12-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0016_questionmodel_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='Answer',
            new_name='answer',
        ),
    ]
