# Generated by Django 3.1.4 on 2021-01-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0013_auto_20201230_0658'),
        ('ITsupermanapp', '0019_auto_20201231_0817'),
    ]

    operations = [
    ]
