# Generated by Django 3.1.3 on 2021-01-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0020_merge_20210103_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
