# Generated by Django 3.1.3 on 2021-01-10 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0022_requestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
