# Generated by Django 3.1.3 on 2021-01-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITsupermanapp', '0024_auto_20210117_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
